-- 코드를 입력하세요
WITH SALES_JAN AS 
(SELECT BOOK_ID, SUM(SALES) AS SALES
FROM BOOK_SALES
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY BOOK_ID
)

SELECT B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,
SUM(SJ.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN SALES_JAN SJ ON B.BOOK_ID = SJ.BOOK_ID
GROUP BY B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC