-- 코드를 입력하세요

--  자동차 종류가 '세단' 또는 'SUV' 인 자동차
--  2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 
--  30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  AND C.CAR_ID NOT IN (
      -- 11월 한 달 동안 대여 이력이 겹치는 차들을 제외
      SELECT CAR_ID 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
  )
GROUP BY C.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;