-- 코드를 작성해주세요

WITH RECURSIVE TMP AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, GENERATION+1 AS GENERATION
    FROM ECOLI_DATA ED
    JOIN TMP T
    ON ED.PARENT_ID = T.ID
)

SELECT COUNT(*) AS COUNT, T.GENERATION
FROM TMP T
JOIN ECOLI_DATA ED
ON T.ID = ED.ID
WHERE T.ID NOT IN 
(
    SELECT PARENT_ID
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY T.GENERATION
ORDER BY T.GENERATION ASC