-- 코드를 작성해주세요


WITH RECURSIVE ECOLI_GEN AS(
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, A.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_GEN A
    ON A.ID = E.PARENT_ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_GEN
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC