-- 생산일자(PRODUCE_DATE)가 2022년 5월
-- 1. 2022년 5월인 product_id, 총 amount

WITH AAA AS
(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
    GROUP BY PRODUCT_ID
)

SELECT FP.PRODUCT_ID,FP.PRODUCT_NAME,
        FP.PRICE * A.TOTAL AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN AAA A ON FP.PRODUCT_ID = A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC