-- 코드를 입력하세요
WITH TMP AS (
SELECT H.HISTORY_ID, C.DAILY_FEE,
    ABS(DATEDIFF(H.START_DATE,H.END_DATE)) +1 AS DURATION,
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭'
)

SELECT T.HISTORY_ID,
ROUND(T.DAILY_FEE * T.DURATION * (1 - IFNULL(DISCOUNT_RATE,0)/100)) AS FEE
FROM TMP T
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON T.DURATION_TYPE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, T.HISTORY_ID DESC
