-- 코드를 입력하세요
WITH RECURSIVE ABC AS(
SELECT 0 AS HOUR
UNION ALL

SELECT HOUR + 1
FROM ABC
WHERE HOUR < 23
)

SELECT A.HOUR, COUNT(HOUR(AO.DATETIME)) AS COUNT
FROM ABC A
LEFT JOIN ANIMAL_OUTS AO
ON HOUR(AO.DATETIME) = A.HOUR
GROUP BY A.HOUR
ORDER BY A.HOUR;