-- 코드를 입력하세요
-- STATUS = DONE , PRICE >- 70만

# SELECT U.USER_ID,U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_USER U
# ON B.WRITER_ID = U.USER_ID
# WHERE B.STATUS = 'DONE' AND B.PRICE  >= 700000
# GROUP BY U.USER_ID
# ORDER BY TOTAL_SALES ASC

SELECT U.USER_ID,U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE' 
GROUP BY U.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES