-- 코드를 입력하세요
WITH A AS (
SELECT MEMBER_ID, DENSE_RANK() OVER (ORDER BY COUNT(*) DESC)
FROM REST_REVIEW
GROUP BY MEMBER_ID
LIMIT 1
)

SELECT MP.MEMBER_NAME	,RR.REVIEW_TEXT	,DATE_FORMAT(RR.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN
    (
        SELECT MEMBER_ID
        FROM A
    )
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC