-- 코드를 작성해주세요
SELECT I2.ITEM_ID, I1.ITEM_NAME, I1.RARITY
FROM ITEM_INFO I1
JOIN ITEM_TREE I2
    ON I1.ITEM_ID = I2.ITEM_ID
WHERE I2.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY I2.ITEM_ID DESC