-- 코드를 작성해주세요
WITH A AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS CNT
FROM ECOLI_DATA 
GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, CNT-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN A AS C
ON C.Y = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC