-- 코드를 입력하세요
WITH A AS (
SELECT CATEGORY, PRODUCT_NAME,PRICE,RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
FROM FOOD_PRODUCT 
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM A
WHERE RNK = 1
GROUP BY CATEGORY
ORDER BY PRICE DESC